language: python

matrix:
  include:
  - python: "pypy"
  - python: "pypy3"
  - python: "2.7"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
install:
  - pip install tox
script:
  - python --version
  - tox -e py,style
